---
title: "STATS.Assignment"
output: html_document
date: "2023-08-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Probability
```{r Probability}

# Part A
r_clicker <- .3
t_clicker <- .7
yes <- .65
no <- .35
r_prob <- .5

truth_yes <- (yes - (r_clicker*r_prob))/t_clicker
cat("The probability of being a Truthful clicker who said yes is", round(truth_yes,2), " ")

# Part B
test_disease <- 0.993
no_disease <- 0.9999
population <- 0.000025
true_pos <- (test_disease * population)
false_pos <- (1-no_disease)*(1-population)
test_positive <- (true_pos+false_pos)

test_pos_disease <- ((population * test_disease) / test_positive)
cat("The probability that someone has a postive test and has the disease is", test_pos_disease)





```



## Wrangling the Billboard Top 100

```{r, Billboard Top 100 Part A}
# Read in Data

billboard <- read.csv("~/Downloads/billboard.csv")
library(ggplot2)
library(tidyverse)
library(dplyr)

# Create table of top 10 most popular songs
# First group by performer and song to make sure songs with same title aren't counted together
# Summarize by counting the number of occurances in the dataset
# Then arrange in decending order and give the top 10
top_10 <- billboard %>% 
  group_by(performer, song) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count)) %>% 
  head(10)

top_10


```


```{r, Billboard Top 100 Part B}
# Plot scatter plot of song diversity over years excluding year 1958 and 2021
library(ggplot2)
library(dplyr)

billboard %>%
   filter(year != "1958" & year != "2021") %>%
   group_by(year) %>%
   summarise(diversity = n_distinct(song)) %>%
   ggplot(aes(x = as.numeric(year), y = diversity)) +
   geom_line(colour = 'blue') +
   xlab("Year") +
   ylab("Number of Distinct Songs per Year") +
   labs(title = "Diversity of Songs Over the Years")
  
```

```{r, Billboard Top 100, Part C}
# Part C

library(dplyr)

billboard <- read.csv("/Users/14072/Downloads/billboard.csv")

songs_10 <- billboard %>%
  filter(weeks_on_chart >= 10)

by_artist <- songs_10 %>%
  group_by(performer) %>%
  summarise(unique_songs = n_distinct(song))

artist_30 <- by_artist %>%
  filter(unique_songs >= 30)

library(ggplot2)

ggplot(data = artist_30, aes(x = reorder(performer, -unique_songs), y = unique_songs)) +
  geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  labs(x = "Performers", y = "Number of Songs", title = "Number of Songs by Performer") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```



```{r, Capital Metro data}
metro <- read.csv('/Users/14072/Downloads/capmetro_UT.csv')

library(ggplot2)

metro$hour_of_day <- factor(metro$hour_of_day, levels = 0:23)
boarding_by_hour_weekend <- aggregate(boarding ~ hour_of_day + weekend, data = metro, mean)

ggplot(boarding_by_hour_weekend, aes(x = hour_of_day, y = boarding, fill = weekend)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(x = "Hour of Day", y = "Average Boarding", title = "Average Boarding by Hour of Day and Weekday/Weekend")
```

```{r, Green Buildings Plot}
library(ggplot2)

ggplot(greenbuildings, aes(x = cluster_rent)) +
  geom_histogram(binwidth = 5, fill = "skyblue", color = "black") +
  labs(title = "Cluster Rent Histogram",
       x = "Clusters",
       y = "Average Rent per Cluster")

ggplot(greenbuildings, aes(x = age, y = Rent)) +
  geom_point(color = "black") +
  geom_smooth(method = "lm", color = "skyblue") +
  labs(title = "Scatterplot with Line",
       x = "Age",
       y = "Rent")

ggplot(greenbuildings, aes(x = factor(renovated), y = age, fill = factor(renovated))) +
  geom_boxplot(color = "skyblue") +
  labs(title = "Box Plots by Renovation Status",
       x = "Renovated",
       y = "Age") +
  scale_x_discrete(labels = c("Not Renovated", "Renovated"))
```


```{r, Clusting & Dimensionality Reduction: PCA}
library(dplyr)
library(stats)
library(pdp)

wine <- read.csv('/Users/14072/Downloads/wine.csv')
head(wine)

continuous_vars <- wine[, 1:11]

pca_result <- prcomp(continuous_vars, scale = TRUE)

#pdf("pca_plot.pdf", width = 10, height = 8)

#plot(pca_result)

v_try = rnorm(2)
v_try = v_try/sqrt(sum(v_try^2))

#plot(pca_result, pch=19, col=rgb(0.3,0.3,0.3,0.3))
#segments(0, 0, v_try[1], v_try[2], col='red', lwd=4)

print(pca_result$rotation)

summary(pca_result)

scores <- as.data.frame(pca_result$x)

pc1_scores <- pca_result$x[, "PC1"]
pc2_scores <- pca_result$x[, "PC2"]

plot(pc1_scores, pc2_scores, 
     xlab = "PC1 Score", ylab = "PC2 Score", 
     main = "Scatter Plot of PC1 vs. PC2")
```

```{r, Clustering & Dimensionality Reduction: tSNE}
```

```{r, Clustering & Dimensionality Reduction: K Means}
```

```{r, Grocery Data}
library(tidyverse)
library(igraph)
library(arules)  # has a big ecosystem of packages built around it
library(arulesViz)
groceries <- readLines("/Users/evanhadd/Downloads/groceries.txt")

items_list <- strsplit(groceries, ",")

# Convert the items list to a transactions object
groceries_trans <- as(items_list, "transactions")


grocrules = apriori(groceries_trans, 
	parameter=list(support=.005, confidence=.2, maxlen=4))

inspect(subset(grocrules, subset=lift > 5))
inspect(subset(grocrules, subset=confidence > 0.6))
inspect(subset(grocrules, subset=lift > 10 & confidence > 0.6))


# Write to a graph file to make a pretty graph later
groceries_graph4 = associations2igraph(subset(grocrules, lift>4), associationsAsNodes = FALSE)
igraph::write_graph(groceries_graph4, file='groceries4.graphml', format = "graphml")

groceries_graph2 = associations2igraph(subset(grocrules, lift>2), associationsAsNodes = FALSE)
igraph::write_graph(groceries_graph2, file='groceries2.graphml', format = "graphml")
```
